### PR TITLE
Finish implementation & add specs

### PR DESCRIPTION
**Pull request by segiddins**
- [x] README

Needed for https://github.com/CocoaPods/CocoaPods/issues/5002.

### CODE REVIEW

**Comment by orta** [comment]
👍🏾 Looks a lot like I'd expect, only extra thing that might be worth adding is a `self.description` that explains what sharding is for users

**Comment by segiddins** [comment]
@orta also planned on sprucing up the readme, but this isn't going to be a default plugin so I really don't expect many users to run into it.

**Comment by orta** [comment]
:+1:

**Comment by segiddins** [comment]
Travis is also now set up!

**Comment by segiddins** [comment]
@CocoaPods/core last chance to review this!

**Comment by nwest** [comment]
Could use a README description 😄

**Comment by alloy** [comment]
Looks good to me 👍

**Comment by neonichu** [comment]
LGTM, but I guess the Gemfile needs an update because of merged branches.

**Comment by segiddins** [comment]
@neonichu yeah was waiting until I had the time to land the rest of these changes simultaneously.

**Pull request merged**
